---
- name: Ensure device roles
  when: (netbox_device_roles | default([])) | length > 0
  loop: "{{ netbox_device_roles }}"
  loop_control:
    label: "{{ item.name }}"
  netbox.netbox.netbox_device_role:
    netbox_url: "{{ nb_common.netbox_url }}"
    netbox_token: "{{ nb_common.netbox_token }}"
    validate_certs: "{{ nb_common.validate_certs }}"
    data:
      name: "{{ item.name }}"
      slug: "{{ item.slug | default(omit) }}"
      color: "{{ item.color | default(omit) }}"
    state: present

