---
- name: Populate NetBox with inventory data
  hosts: localhost
  gather_facts: false

  vars:
    nb_common:
      netbox_url: "{{ netbox_url }}"
      netbox_token: "{{ (lookup('ansible.builtin.env', 'NETBOX_TOKEN') | default('', true)) | length > 0 | ternary(lookup('ansible.builtin.env', 'NETBOX_TOKEN'), (lookup('ansible.builtin.file', lookup('ansible.builtin.env','HOME') + '/.netbox_token') | trim)) }}"
      validate_certs: "{{ netbox_validate_certs }}"

  pre_tasks:
    - name: Load data files under data/
      ansible.builtin.include_vars:
        dir: "{{ playbook_dir }}/../data"
        extensions:
          - yml
          - yaml

  roles:
    - role: netbox_populate

